development:
  adapter: sqlite3
  database: db/peppermill_development.sqlite3
  pool: 5
  timeout: 5000

staging:
  adapter: sqlite3
  database: db/peppermill_staging.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/peppermill_production.sqlite3
  pool: 5
  timeout: 5000

test: &test
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
